#!/usr/bin/with-contenv bash
cat <<"EOF"
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
         _               _
    __ _| |__   ___  ___| |_
   / _` | '_ \ / _ \/ __| __/
  | (_| | | | | (_) \__ \ |_
   \__, |_| |_|\___/|___/\__|
   |___/      /   _ \
          (¯\| o (@) |/¯)
           \_  .___.  _/
            /   !_!   \
           /_.--._.--._\

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
EOF

TRANS_WEBUI_USER=${TRANS_WEBUI_USER:-admin}
TRANS_WEBUI_PASS=${TRANS_WEBUI_PASS:-adminadmin}
TRANS_WEBUI_PORT=${TRANS_WEBUI_PORT:-9091}
TRANS_CONNECTION_PORT=${TRANS_CONNECTION_PORT:-51413}

# rpc-authentication-required should always be true
# if it is not true, assume the settings.json is invalid and needs to be replaced
RPC_AUTH=$(jq '."rpc-authentication-required"' /config/settings.json)
if ! ((RPC_AUTH)); then
    cp /usr/local/bin/settings.json /config/settings.json
fi

# set custom settings
sed -i -E "s|\"peer-port\":.*$|\"peer-port\": $TRANS_CONNECTION_PORT,|g" /config/settings.json 
sed -i -E "s|\"rpc-username\":.*$|\"rpc-username\": \"$TRANS_WEBUI_USER\",|g" /config/settings.json 
sed -i -E "s|\"rpc-password\":.*$|\"rpc-password\": \"$TRANS_WEBUI_PASS\",|g" /config/settings.json 
sed -i -E "s|\"rpc-port\":.*$|\"rpc-port\": $TRANS_WEBUI_PORT,|g" /config/settings.json 

# only chown the /downloads directory if it is not owned by abc:abc
CHOWN_DIR=/downloads
DIR_OWNER=`stat -c "%U:%G" $CHOWN_DIR`
if [[ $DIR_OWNER != "abc:abc" ]]
then
    echo "chowning $CHOWN_DIR please be patient"
    chown -R abc:abc $CHOWN_DIR
fi

# only chown the /config directory if it is not owned by abc:abc
CHOWN_DIR=/config
DIR_OWNER=`stat -c "%U:%G" $CHOWN_DIR`
if [[ $DIR_OWNER != "abc:abc" ]]
then
    echo "chowning $CHOWN_DIR please be patient"
    chown -R abc:abc $CHOWN_DIR
fi
