#!/usr/bin/with-contenv bash

TRANS_WEBUI_USER=${TRANS_WEBUI_USER:-admin}
TRANS_WEBUI_PASS=${TRANS_WEBUI_PASS:-adminadmin}
TRANS_WEBUI_PORT=${TRANS_WEBUI_PORT:-9091}
TRANS_CONNECTION_PORT=${TRANS_CONNECTION_PORT:-51413}

CONFIG_FILE="/config/settings.json"
CONFIG_STR=$(cat <<'HEREDOC'
{
    "alt-speed-down": 50,
    "alt-speed-enabled": false,
    "alt-speed-time-begin": 540,
    "alt-speed-time-day": 127,
    "alt-speed-time-enabled": false,
    "alt-speed-time-end": 1020,
    "alt-speed-up": 50,
    "bind-address-ipv4": "0.0.0.0",
    "bind-address-ipv6": "::",
    "blocklist-enabled": false,
    "blocklist-url": "http://www.example.com/blocklist",
    "cache-size-mb": 4,
    "dht-enabled": true,
    "download-dir": "/downloads/complete",
    "download-queue-enabled": false,
    "download-queue-size": 5,
    "encryption": 1,
    "idle-seeding-limit": 30,
    "idle-seeding-limit-enabled": false,
    "incomplete-dir": "/downloads/incomplete",
    "incomplete-dir-enabled": true,
    "lpd-enabled": true,
    "message-level": 2,
    "peer-congestion-algorithm": "",
    "peer-id-ttl-hours": 6,
    "peer-limit-global": 2000,
    "peer-limit-per-torrent": 200,
    "peer-port": CONN_PORT,
    "peer-port-random-high": 65535,
    "peer-port-random-low": 49152,
    "peer-port-random-on-start": false,
    "peer-socket-tos": "default",
    "pex-enabled": true,
    "port-forwarding-enabled": true,
    "preallocation": 1,
    "prefetch-enabled": true,
    "queue-stalled-enabled": true,
    "queue-stalled-minutes": 30,
    "ratio-limit": 2,
    "ratio-limit-enabled": false,
    "rename-partial-files": true,
    "rpc-authentication-required": true,
    "rpc-bind-address": "0.0.0.0",
    "rpc-enabled": true,
    "rpc-host-whitelist": "",
    "rpc-host-whitelist-enabled": true,
    "rpc-password": "WEBUI_PASS",
    "rpc-port": WEBUI_PORT,
    "rpc-url": "/transmission/",
    "rpc-username": "WEBUI_USER",
    "rpc-whitelist": "127.0.0.1",
    "rpc-whitelist-enabled": false,
    "scrape-paused-torrents-enabled": true,
    "script-torrent-done-enabled": true,
    "script-torrent-done-filename": "/usr/local/bin/transmission-postprocess.sh",
    "seed-queue-enabled": false,
    "seed-queue-size": 10,
    "speed-limit-down": 100,
    "speed-limit-down-enabled": false,
    "speed-limit-up": 100,
    "speed-limit-up-enabled": false,
    "start-added-torrents": true,
    "trash-original-torrent-files": false,
    "umask": 2,
    "upload-slots-per-torrent": 50,
    "utp-enabled": true,
    "watch-dir": "/watch",
    "watch-dir-enabled": false
}
HEREDOC
)

CONFIG_STR=${CONFIG_STR/WEBUI_USER/$TRANS_WEBUI_USER}
CONFIG_STR=${CONFIG_STR/WEBUI_PASS/$TRANS_WEBUI_PASS}
CONFIG_STR=${CONFIG_STR/WEBUI_PORT/$TRANS_WEBUI_PORT}
CONFIG_STR=${CONFIG_STR/CONN_PORT/$TRANS_CONNECTION_PORT}

rm /config/settings.json
echo "$CONFIG_STR" > /config/settings.json

cat <<"EOF"
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
         _               _
    __ _| |__   ___  ___| |_
   / _` | '_ \ / _ \/ __| __/
  | (_| | | | | (_) \__ \ |_
   \__, |_|_|_|\___/|___/\__|
   |___/      /   _ \
          (¯\| o (@) |/¯)
           \_  .___.  _/
            /   !_!   \
           /_.--._.--._\

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
EOF

# take control of permissions
chown -R abc:abc \
        /config \
        /downloads
